# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    branches:
    - master
    paths:
    - 'src/**'
    
env:
  HASH: $(git rev-parse --short "$GITHUB_SHA")
  BRANCH: ${GITHUB_REF##*/}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get the version
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
        
      - name: Deploy to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          dockerfile: ./src/Tweeter/Dockerfile
          gcloud_service_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: ${{ secrets.SERVICE_NAME }}
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
